CREATE TABLE CUSTOMER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(50),
    IDENTIFIER INTEGER NOT NULL,
    LAST_NAME VARCHAR(50)
);
COMMENT ON COLUMN CUSTOMER.ID IS '';
COMMENT ON COLUMN CUSTOMER.FIRST_NAME IS '';
COMMENT ON COLUMN CUSTOMER.IDENTIFIER IS '';
COMMENT ON COLUMN CUSTOMER.LAST_NAME IS '';
CREATE UNIQUE INDEX UK_34Y40Q5CFKB60PU0D5L9X3LSK_INDEX_5 ON CUSTOMER (IDENTIFIER);

CREATE TABLE ACCOUNT
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BALANCE INTEGER NOT NULL,
    ACCOUNT_NO INTEGER NOT NULL,
    ID_CUSTOMER BIGINT
);
COMMENT ON COLUMN ACCOUNT.ID IS '';
COMMENT ON COLUMN ACCOUNT.BALANCE IS '';
COMMENT ON COLUMN ACCOUNT.ACCOUNT_NO IS '';
COMMENT ON COLUMN ACCOUNT.ID_CUSTOMER IS '';
CREATE UNIQUE INDEX UK_FQVKH5VLRNCY7C0DJ25OS0WAM_INDEX_A ON ACCOUNT (ACCOUNT_NO);

